import json
from collections import defaultdict


employees = [
    {
        "clock": "48460",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "n776ana6s32jilz",
        "id": "yq16faj88muj639",
        "last_name": "MEZA GONZALEZ",
        "line": "J01",
        "name": "CRISTIAN",
        "output": "PACKING",
        "position": "TECNICO SMT",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "69587",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "caxbail7415v_cmsEFQj2vb.jpg",
        "employee_id": "dmgi2ffiux11461",
        "id": "p5a5vw3nnb0xtsb",
        "last_name": "RIVERA LOPEZ",
        "line": "J01",
        "name": "CARLOS MIGUEL",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "45679",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "ceqdfn7574Qo_S4O074Ftrf.jpg",
        "employee_id": "ylmt13qnfzpwrv0",
        "id": "6uk6k1o1o8ivta7",
        "last_name": "SALCIDO RUIZ",
        "line": "J01",
        "name": "CESAR",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "69587",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "caxbail7415v_cmsEFQj2vb.jpg",
        "employee_id": "dmgi2ffiux11461",
        "id": "xiggoyn8mxuwbxo",
        "last_name": "RIVERA LOPEZ",
        "line": "J02",
        "name": "CARLOS MIGUEL",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "45679",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "ceqdfn7574Qo_S4O074Ftrf.jpg",
        "employee_id": "ylmt13qnfzpwrv0",
        "id": "ha8xh689h0mdwqr",
        "last_name": "SALCIDO RUIZ",
        "line": "J02",
        "name": "CESAR",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "57347",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "hbr72l9rrhW_8yej6QpKWC.jpg",
        "employee_id": "1f5js6vs8hantqb",
        "id": "6s5e8kolimsd8nd",
        "last_name": "LIRA RAMIREZ",
        "line": "J06",
        "name": "HERIBERTO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "65995",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "d2I1mTYO52c_sHA18f1LxI.jpg",
        "employee_id": "n1eice874pp95hg",
        "id": "uu06a0fos9o5k9t",
        "last_name": "LOPEZ ESCOBAR",
        "line": "J08",
        "name": "DANIEL OBED",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "57347",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "hbr72l9rrhW_8yej6QpKWC.jpg",
        "employee_id": "1f5js6vs8hantqb",
        "id": "21iwzf5b6ljtk5o",
        "last_name": "LIRA RAMIREZ",
        "line": "J08",
        "name": "HERIBERTO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "65995",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "d2I1mTYO52c_sHA18f1LxI.jpg",
        "employee_id": "n1eice874pp95hg",
        "id": "osv9ckdbhxqqdsr",
        "last_name": "LOPEZ ESCOBAR",
        "line": "J09",
        "name": "DANIEL OBED",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "57347",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "hbr72l9rrhW_8yej6QpKWC.jpg",
        "employee_id": "1f5js6vs8hantqb",
        "id": "ysin42ojnljo8sa",
        "last_name": "LIRA RAMIREZ",
        "line": "J09",
        "name": "HERIBERTO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "6ulm5h5b10n9hd8",
        "last_name": "BHUSHAN",
        "line": "J01",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "",
        "id": "1u1ggazk48beae7",
        "last_name": "",
        "line": "J01",
        "name": "",
        "output": "SMT_OUT",
        "position": "",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "",
        "id": "8ptgokdgvsij0u4",
        "last_name": "",
        "line": "J02",
        "name": "",
        "output": "SMT_OUT",
        "position": "",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "di8ordr3wm7zv1u",
        "last_name": "BHUSHAN",
        "line": "J02",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "",
        "id": "yelr61vhp86amf3",
        "last_name": "",
        "line": "J06",
        "name": "",
        "output": "SMT_OUT",
        "position": "",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "xv9ihfkatgtxfwk",
        "last_name": "BHUSHAN",
        "line": "J06",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "",
        "id": "u0npq85uw1bw1la",
        "last_name": "",
        "line": "J08",
        "name": "",
        "output": "SMT_OUT",
        "position": "",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "f6kpel9dy9xii8b",
        "last_name": "BHUSHAN",
        "line": "J08",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "",
        "id": "808s476iznv5i61",
        "last_name": "",
        "line": "J09",
        "name": "",
        "output": "SMT_OUT",
        "position": "",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "67i7twkesde36wy",
        "last_name": "BHUSHAN",
        "line": "J09",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46540",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "yxenryz1npzaf3v",
        "id": "biv6lqvaybf65ce",
        "last_name": "AVILA CASTRO",
        "line": "J01",
        "name": "SALVADOR",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46540",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "yxenryz1npzaf3v",
        "id": "namek0x77pnnmdx",
        "last_name": "AVILA CASTRO",
        "line": "J02",
        "name": "SALVADOR",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46430",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "4rgzrt94gb2uh7k",
        "id": "o262wpf148wds6b",
        "last_name": "MERCADO CABELLO",
        "line": "J01",
        "name": "MIGUEL ANGEL",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46430",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "4rgzrt94gb2uh7k",
        "id": "0nnvs4feo4xy1l5",
        "last_name": "MERCADO CABELLO",
        "line": "J02",
        "name": "MIGUEL ANGEL",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46430",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "4rgzrt94gb2uh7k",
        "id": "jnj9a5pcbb5cqvg",
        "last_name": "MERCADO CABELLO",
        "line": "J06",
        "name": "MIGUEL ANGEL",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46540",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "yxenryz1npzaf3v",
        "id": "534n8bq12ekcg00",
        "last_name": "AVILA CASTRO",
        "line": "J06",
        "name": "SALVADOR",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46430",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "4rgzrt94gb2uh7k",
        "id": "dyr9rut7i4dhw07",
        "last_name": "MERCADO CABELLO",
        "line": "J08",
        "name": "MIGUEL ANGEL",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46540",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "yxenryz1npzaf3v",
        "id": "udzdcn6nfnlq6us",
        "last_name": "AVILA CASTRO",
        "line": "J08",
        "name": "SALVADOR",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46430",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "4rgzrt94gb2uh7k",
        "id": "4j7bac7a6ejtrn9",
        "last_name": "MERCADO CABELLO",
        "line": "J09",
        "name": "MIGUEL ANGEL",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46540",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "yxenryz1npzaf3v",
        "id": "j430bo7w4lh0nzp",
        "last_name": "AVILA CASTRO",
        "line": "J09",
        "name": "SALVADOR",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "45679",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "ceqdfn7574Qo_S4O074Ftrf.jpg",
        "employee_id": "ylmt13qnfzpwrv0",
        "id": "pwf1cf5gbig0eg5",
        "last_name": "SALCIDO RUIZ",
        "line": "J01",
        "name": "CESAR",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "69587",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "caxbail7415v_cmsEFQj2vb.jpg",
        "employee_id": "dmgi2ffiux11461",
        "id": "o1uy3yu88hko2hn",
        "last_name": "RIVERA LOPEZ",
        "line": "J01",
        "name": "CARLOS MIGUEL",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46430",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "4rgzrt94gb2uh7k",
        "id": "wy0akpd0xqym7iv",
        "last_name": "MERCADO CABELLO",
        "line": "J01",
        "name": "MIGUEL ANGEL",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46540",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "yxenryz1npzaf3v",
        "id": "vxj0oxqcfya8j62",
        "last_name": "AVILA CASTRO",
        "line": "J01",
        "name": "SALVADOR",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "",
        "id": "pb9fy19tzxssovt",
        "last_name": "",
        "line": "J01",
        "name": "",
        "output": "SMT_OUT",
        "position": "",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "45679",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "ceqdfn7574Qo_S4O074Ftrf.jpg",
        "employee_id": "ylmt13qnfzpwrv0",
        "id": "w2onzjyqw29e0bu",
        "last_name": "SALCIDO RUIZ",
        "line": "J02",
        "name": "CESAR",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "69587",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "caxbail7415v_cmsEFQj2vb.jpg",
        "employee_id": "dmgi2ffiux11461",
        "id": "nxlekkwgdr1ng0z",
        "last_name": "RIVERA LOPEZ",
        "line": "J02",
        "name": "CARLOS MIGUEL",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "",
        "id": "7mttw0p5yg213sx",
        "last_name": "",
        "line": "J02",
        "name": "",
        "output": "SMT_OUT",
        "position": "",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46430",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "4rgzrt94gb2uh7k",
        "id": "315uy4hkpvw1nil",
        "last_name": "MERCADO CABELLO",
        "line": "J02",
        "name": "MIGUEL ANGEL",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46540",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "yxenryz1npzaf3v",
        "id": "n47h8jvvqh8cseu",
        "last_name": "AVILA CASTRO",
        "line": "J02",
        "name": "SALVADOR",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "",
        "id": "saq5qst6blq0o08",
        "last_name": "",
        "line": "J06",
        "name": "",
        "output": "SMT_OUT",
        "position": "",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "57347",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "hbr72l9rrhW_8yej6QpKWC.jpg",
        "employee_id": "1f5js6vs8hantqb",
        "id": "h8u419fkl9ddpkq",
        "last_name": "LIRA RAMIREZ",
        "line": "J06",
        "name": "HERIBERTO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "65995",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "d2I1mTYO52c_sHA18f1LxI.jpg",
        "employee_id": "n1eice874pp95hg",
        "id": "lkcdffcpz4y96kp",
        "last_name": "LOPEZ ESCOBAR",
        "line": "J06",
        "name": "DANIEL OBED",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46540",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "yxenryz1npzaf3v",
        "id": "xw7ae4p3m1lo2ye",
        "last_name": "AVILA CASTRO",
        "line": "J06",
        "name": "SALVADOR",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46430",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "4rgzrt94gb2uh7k",
        "id": "386lfpi7406nru9",
        "last_name": "MERCADO CABELLO",
        "line": "J06",
        "name": "MIGUEL ANGEL",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46430",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "4rgzrt94gb2uh7k",
        "id": "ygscesu5ls4jywl",
        "last_name": "MERCADO CABELLO",
        "line": "J08",
        "name": "MIGUEL ANGEL",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46540",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "yxenryz1npzaf3v",
        "id": "sbhnn36pbft1fks",
        "last_name": "AVILA CASTRO",
        "line": "J08",
        "name": "SALVADOR",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "65995",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "d2I1mTYO52c_sHA18f1LxI.jpg",
        "employee_id": "n1eice874pp95hg",
        "id": "cbq0oqjm8kqzzga",
        "last_name": "LOPEZ ESCOBAR",
        "line": "J08",
        "name": "DANIEL OBED",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "57347",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "hbr72l9rrhW_8yej6QpKWC.jpg",
        "employee_id": "1f5js6vs8hantqb",
        "id": "de9o37zvk3c49om",
        "last_name": "LIRA RAMIREZ",
        "line": "J08",
        "name": "HERIBERTO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46430",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "4rgzrt94gb2uh7k",
        "id": "f7he2n67m3x9qsg",
        "last_name": "MERCADO CABELLO",
        "line": "J09",
        "name": "MIGUEL ANGEL",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46540",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "yxenryz1npzaf3v",
        "id": "c1psfhqwrirsk5r",
        "last_name": "AVILA CASTRO",
        "line": "J09",
        "name": "SALVADOR",
        "output": "SMT_OUT",
        "position": "INGENIERO",
        "record_position": "INGENIERO",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "57347",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "hbr72l9rrhW_8yej6QpKWC.jpg",
        "employee_id": "1f5js6vs8hantqb",
        "id": "irqk2wly8meqtyv",
        "last_name": "LIRA RAMIREZ",
        "line": "J09",
        "name": "HERIBERTO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "65995",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "d2I1mTYO52c_sHA18f1LxI.jpg",
        "employee_id": "n1eice874pp95hg",
        "id": "oa2ic1hw4tjwevy",
        "last_name": "LOPEZ ESCOBAR",
        "line": "J09",
        "name": "DANIEL OBED",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "",
        "id": "64h7o0lda3vvbxd",
        "last_name": "",
        "line": "J09",
        "name": "",
        "output": "SMT_OUT",
        "position": "",
        "record_position": "TECNICO SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "69587",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "caxbail7415v_cmsEFQj2vb.jpg",
        "employee_id": "dmgi2ffiux11461",
        "id": "dapu8i1eelcrspd",
        "last_name": "RIVERA LOPEZ",
        "line": "J01",
        "name": "CARLOS MIGUEL",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "45679",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "ceqdfn7574Qo_S4O074Ftrf.jpg",
        "employee_id": "ylmt13qnfzpwrv0",
        "id": "44ddpa0i7l9bauu",
        "last_name": "SALCIDO RUIZ",
        "line": "J02",
        "name": "CESAR",
        "output": "PACKING",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "45679",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "ceqdfn7574Qo_S4O074Ftrf.jpg",
        "employee_id": "ylmt13qnfzpwrv0",
        "id": "uzrncx0o2jg2ls7",
        "last_name": "SALCIDO RUIZ",
        "line": "J03",
        "name": "CESAR",
        "output": "PACKING",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "57347",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "hbr72l9rrhW_8yej6QpKWC.jpg",
        "employee_id": "1f5js6vs8hantqb",
        "id": "z3fq1mgeqq9wynl",
        "last_name": "LIRA RAMIREZ",
        "line": "J05",
        "name": "HERIBERTO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "57347",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "hbr72l9rrhW_8yej6QpKWC.jpg",
        "employee_id": "1f5js6vs8hantqb",
        "id": "36mjni3nqw0xhwg",
        "last_name": "LIRA RAMIREZ",
        "line": "J06",
        "name": "HERIBERTO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "65995",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "d2I1mTYO52c_sHA18f1LxI.jpg",
        "employee_id": "n1eice874pp95hg",
        "id": "6ygivlh8gtgrqia",
        "last_name": "LOPEZ ESCOBAR",
        "line": "J08",
        "name": "DANIEL OBED",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46070",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "",
        "employee_id": "qtt7jys7efm9olr",
        "id": "7vwa5wdbpyosx3s",
        "last_name": "FIERRO",
        "line": "J01",
        "name": "ARTURO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "l8o77k2utlen8bu",
        "last_name": "BHUSHAN",
        "line": "J02",
        "name": "SHASHI",
        "output": "PACKING",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "lx3hww15j63okmb",
        "last_name": "BHUSHAN",
        "line": "J05",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "ddyhu5rs0s7vsxe",
        "last_name": "BHUSHAN",
        "line": "J08",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46070",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "",
        "employee_id": "qtt7jys7efm9olr",
        "id": "jkkwp1084ag15nd",
        "last_name": "FIERRO",
        "line": "J03",
        "name": "ARTURO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46070",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "",
        "employee_id": "qtt7jys7efm9olr",
        "id": "gtr47uxlts6vrr5",
        "last_name": "FIERRO",
        "line": "J06",
        "name": "ARTURO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "48460",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "",
        "employee_id": "n776ana6s32jilz",
        "id": "hs3ppkr13ipntda",
        "last_name": "MEZA GONZALEZ",
        "line": "J01",
        "name": "CRISTIAN",
        "output": "PACKING",
        "position": "TECNICO SMT",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "73493",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "",
        "employee_id": "a7x0i679nuxxi4i",
        "id": "r0ouge780g78ezw",
        "last_name": "ORDOÑEZ MIRANDA",
        "line": "J02",
        "name": "CARLOS MANUEL",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "93257",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "dylan_gcp6DqxEVX.jpg",
        "employee_id": "m28qx9fo00izf74",
        "id": "j3fu4d4aaddq5gv",
        "last_name": "TORRES SERRANO",
        "line": "J03",
        "name": "DYLAN ARTURO",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "93252",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "daniel_hFJYvQYSuX.jpg",
        "employee_id": "z9en4fltqn4wqin",
        "id": "obiv1q1pgrmn948",
        "last_name": "HERNANDEZ",
        "line": "J05",
        "name": "JAVIER DANIEL",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "93258",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "carlos_WgytRMX6ti.jpg",
        "employee_id": "t6y98g8myajd6hu",
        "id": "h7fe2f0db7owmys",
        "last_name": "VILLEGAS RODRIGUEZ",
        "line": "J06",
        "name": "CARLOS ABRAHAM",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "6234",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-19",
        "employee_avatar": "",
        "employee_id": "gsjtvyiwtihf45z",
        "id": "p2ssj5ywz2srttl",
        "last_name": "SAAVEDRA OLIVEROS",
        "line": "J08",
        "name": "JUAN LUIS",
        "output": "PACKING",
        "position": "TECNICO SMT",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "69587",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "caxbail7415v_cmsEFQj2vb.jpg",
        "employee_id": "dmgi2ffiux11461",
        "id": "ljlgdx4dj9uqulb",
        "last_name": "RIVERA LOPEZ",
        "line": "J01",
        "name": "CARLOS MIGUEL",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "45679",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "ceqdfn7574Qo_S4O074Ftrf.jpg",
        "employee_id": "ylmt13qnfzpwrv0",
        "id": "7jlv83clolicq91",
        "last_name": "SALCIDO RUIZ",
        "line": "J02",
        "name": "CESAR",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "45679",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "ceqdfn7574Qo_S4O074Ftrf.jpg",
        "employee_id": "ylmt13qnfzpwrv0",
        "id": "t6tmgz6zr9dnyg5",
        "last_name": "SALCIDO RUIZ",
        "line": "J03",
        "name": "CESAR",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "57347",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "hbr72l9rrhW_8yej6QpKWC.jpg",
        "employee_id": "1f5js6vs8hantqb",
        "id": "39mlb9aaaxzs6r6",
        "last_name": "LIRA RAMIREZ",
        "line": "J05",
        "name": "HERIBERTO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "57347",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "hbr72l9rrhW_8yej6QpKWC.jpg",
        "employee_id": "1f5js6vs8hantqb",
        "id": "n715jm66wr2zeq8",
        "last_name": "LIRA RAMIREZ",
        "line": "J06",
        "name": "HERIBERTO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "65995",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "d2I1mTYO52c_sHA18f1LxI.jpg",
        "employee_id": "n1eice874pp95hg",
        "id": "fynvltzm5jqzu8i",
        "last_name": "LOPEZ ESCOBAR",
        "line": "J08",
        "name": "DANIEL OBED",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46070",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "",
        "employee_id": "qtt7jys7efm9olr",
        "id": "ig8t449noxnp9cl",
        "last_name": "FIERRO",
        "line": "J01",
        "name": "ARTURO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "d1o42dqdmouqfzv",
        "last_name": "BHUSHAN",
        "line": "J02",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46070",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "",
        "employee_id": "qtt7jys7efm9olr",
        "id": "etgy88auxwayvvh",
        "last_name": "FIERRO",
        "line": "J03",
        "name": "ARTURO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "caolbbmappsf0xq",
        "last_name": "BHUSHAN",
        "line": "J05",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46070",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "",
        "employee_id": "qtt7jys7efm9olr",
        "id": "ej5progwimaue5z",
        "last_name": "FIERRO",
        "line": "J06",
        "name": "ARTURO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "tzbztsia5u82zlb",
        "last_name": "BHUSHAN",
        "line": "J08",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "48460",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "",
        "employee_id": "n776ana6s32jilz",
        "id": "wnyfssxugcg9d5h",
        "last_name": "MEZA GONZALEZ",
        "line": "J01",
        "name": "CRISTIAN",
        "output": "PACKING",
        "position": "TECNICO SMT",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "73493",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "",
        "employee_id": "a7x0i679nuxxi4i",
        "id": "t4lah13ke8l87vc",
        "last_name": "ORDOÑEZ MIRANDA",
        "line": "J02",
        "name": "CARLOS MANUEL",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "93257",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "dylan_gcp6DqxEVX.jpg",
        "employee_id": "m28qx9fo00izf74",
        "id": "y54px315k8v96ci",
        "last_name": "TORRES SERRANO",
        "line": "J03",
        "name": "DYLAN ARTURO",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "93252",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "daniel_hFJYvQYSuX.jpg",
        "employee_id": "z9en4fltqn4wqin",
        "id": "svfmkuimedh8wik",
        "last_name": "HERNANDEZ",
        "line": "J05",
        "name": "JAVIER DANIEL",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "93258",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "carlos_WgytRMX6ti.jpg",
        "employee_id": "t6y98g8myajd6hu",
        "id": "gfper4n2ze21msh",
        "last_name": "VILLEGAS RODRIGUEZ",
        "line": "J06",
        "name": "CARLOS ABRAHAM",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "6234",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-20",
        "employee_avatar": "",
        "employee_id": "gsjtvyiwtihf45z",
        "id": "c3t7wvuxsjbk6vk",
        "last_name": "SAAVEDRA OLIVEROS",
        "line": "J08",
        "name": "JUAN LUIS",
        "output": "PACKING",
        "position": "TECNICO SMT",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "69587",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "caxbail7415v_cmsEFQj2vb.jpg",
        "employee_id": "dmgi2ffiux11461",
        "id": "lj6gy0jlm9xmiuh",
        "last_name": "RIVERA LOPEZ",
        "line": "J01",
        "name": "CARLOS MIGUEL",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "45679",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "ceqdfn7574Qo_S4O074Ftrf.jpg",
        "employee_id": "ylmt13qnfzpwrv0",
        "id": "vw51cqk8byod5b1",
        "last_name": "SALCIDO RUIZ",
        "line": "J02",
        "name": "CESAR",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "45679",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "ceqdfn7574Qo_S4O074Ftrf.jpg",
        "employee_id": "ylmt13qnfzpwrv0",
        "id": "zib66nkz7rtyqzx",
        "last_name": "SALCIDO RUIZ",
        "line": "J03",
        "name": "CESAR",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "57347",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "hbr72l9rrhW_8yej6QpKWC.jpg",
        "employee_id": "1f5js6vs8hantqb",
        "id": "z1mdews94gslawx",
        "last_name": "LIRA RAMIREZ",
        "line": "J05",
        "name": "HERIBERTO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "57347",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "hbr72l9rrhW_8yej6QpKWC.jpg",
        "employee_id": "1f5js6vs8hantqb",
        "id": "hob3fasnq0gdy29",
        "last_name": "LIRA RAMIREZ",
        "line": "J06",
        "name": "HERIBERTO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "65995",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "d2I1mTYO52c_sHA18f1LxI.jpg",
        "employee_id": "n1eice874pp95hg",
        "id": "bdm54jelahw1ywf",
        "last_name": "LOPEZ ESCOBAR",
        "line": "J08",
        "name": "DANIEL OBED",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46070",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "qtt7jys7efm9olr",
        "id": "bdf0jrxh3ostk6n",
        "last_name": "FIERRO",
        "line": "J01",
        "name": "ARTURO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "4c6y1ajhegp5swo",
        "last_name": "BHUSHAN",
        "line": "J02",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46070",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "qtt7jys7efm9olr",
        "id": "t3dbujogul4l53k",
        "last_name": "FIERRO",
        "line": "J03",
        "name": "ARTURO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "01li3z5cmye00x9",
        "last_name": "BHUSHAN",
        "line": "J05",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46070",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "qtt7jys7efm9olr",
        "id": "iqrr6922z5gximt",
        "last_name": "FIERRO",
        "line": "J06",
        "name": "ARTURO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "hmoea3kconjwefp",
        "last_name": "BHUSHAN",
        "line": "J08",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "73493",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "a7x0i679nuxxi4i",
        "id": "ojo96s00w2402vh",
        "last_name": "ORDOÑEZ MIRANDA",
        "line": "J02",
        "name": "CARLOS MANUEL",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "93257",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "dylan_gcp6DqxEVX.jpg",
        "employee_id": "m28qx9fo00izf74",
        "id": "rk2fmipqkpnywvv",
        "last_name": "TORRES SERRANO",
        "line": "J03",
        "name": "DYLAN ARTURO",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "93252",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "daniel_hFJYvQYSuX.jpg",
        "employee_id": "z9en4fltqn4wqin",
        "id": "09reo76f51k7d8a",
        "last_name": "HERNANDEZ",
        "line": "J05",
        "name": "JAVIER DANIEL",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "93258",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "carlos_WgytRMX6ti.jpg",
        "employee_id": "t6y98g8myajd6hu",
        "id": "fg279lsz7r7p7n4",
        "last_name": "VILLEGAS RODRIGUEZ",
        "line": "J06",
        "name": "CARLOS ABRAHAM",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "6234",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-21",
        "employee_avatar": "",
        "employee_id": "gsjtvyiwtihf45z",
        "id": "uj2moxeys0c62j8",
        "last_name": "SAAVEDRA OLIVEROS",
        "line": "J08",
        "name": "JUAN LUIS",
        "output": "PACKING",
        "position": "TECNICO SMT",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "69587",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "caxbail7415v_cmsEFQj2vb.jpg",
        "employee_id": "dmgi2ffiux11461",
        "id": "c6hoj89xc2u2v5k",
        "last_name": "RIVERA LOPEZ",
        "line": "J01",
        "name": "CARLOS MIGUEL",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "45679",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "ceqdfn7574Qo_S4O074Ftrf.jpg",
        "employee_id": "ylmt13qnfzpwrv0",
        "id": "cijgcyi2zqfo8w4",
        "last_name": "SALCIDO RUIZ",
        "line": "J02",
        "name": "CESAR",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "45679",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "ceqdfn7574Qo_S4O074Ftrf.jpg",
        "employee_id": "ylmt13qnfzpwrv0",
        "id": "q9lkcc6x4kskd9r",
        "last_name": "SALCIDO RUIZ",
        "line": "J03",
        "name": "CESAR",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "57347",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "hbr72l9rrhW_8yej6QpKWC.jpg",
        "employee_id": "1f5js6vs8hantqb",
        "id": "bcmam06abo14fdv",
        "last_name": "LIRA RAMIREZ",
        "line": "J05",
        "name": "HERIBERTO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "57347",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "hbr72l9rrhW_8yej6QpKWC.jpg",
        "employee_id": "1f5js6vs8hantqb",
        "id": "8h80u7cubwr2dva",
        "last_name": "LIRA RAMIREZ",
        "line": "J06",
        "name": "HERIBERTO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "65995",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "d2I1mTYO52c_sHA18f1LxI.jpg",
        "employee_id": "n1eice874pp95hg",
        "id": "sjrfphvummkbent",
        "last_name": "LOPEZ ESCOBAR",
        "line": "J08",
        "name": "DANIEL OBED",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "EE_SMT",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46070",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "qtt7jys7efm9olr",
        "id": "mtya7jxang7108u",
        "last_name": "FIERRO",
        "line": "J01",
        "name": "ARTURO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46070",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "qtt7jys7efm9olr",
        "id": "najwdjoqx7w293n",
        "last_name": "FIERRO",
        "line": "J03",
        "name": "ARTURO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "46070",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "qtt7jys7efm9olr",
        "id": "xvg2ztuw3obyhz5",
        "last_name": "FIERRO",
        "line": "J06",
        "name": "ARTURO",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "14c2v6n8l8u8ywa",
        "last_name": "BHUSHAN",
        "line": "J02",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "b3ywtvcug52tfq4",
        "last_name": "BHUSHAN",
        "line": "J05",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "64902",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "whats_app_image_2024_11_07_at_15_30_02_056f5de4_m1vzfnIzWH.jpg",
        "employee_id": "t44lw2ijr1pk8h1",
        "id": "vbu0n1uasx5qw16",
        "last_name": "BHUSHAN",
        "line": "J08",
        "name": "SHASHI",
        "output": "SMT_OUT",
        "position": "TECNICO SMT",
        "record_position": "PR",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "48460",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "n776ana6s32jilz",
        "id": "44r5zgil5pkul1t",
        "last_name": "MEZA GONZALEZ",
        "line": "J01",
        "name": "CRISTIAN",
        "output": "PACKING",
        "position": "TECNICO SMT",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "73493",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "a7x0i679nuxxi4i",
        "id": "geek2s16e5klvyz",
        "last_name": "ORDOÑEZ MIRANDA",
        "line": "J02",
        "name": "CARLOS MANUEL",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "93257",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "dylan_gcp6DqxEVX.jpg",
        "employee_id": "m28qx9fo00izf74",
        "id": "a68w3ujd7j7q1l4",
        "last_name": "TORRES SERRANO",
        "line": "J03",
        "name": "DYLAN ARTURO",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "93252",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "daniel_hFJYvQYSuX.jpg",
        "employee_id": "z9en4fltqn4wqin",
        "id": "4lwlhko980wzytd",
        "last_name": "HERNANDEZ",
        "line": "J05",
        "name": "JAVIER DANIEL",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "93258",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "carlos_WgytRMX6ti.jpg",
        "employee_id": "t6y98g8myajd6hu",
        "id": "2ev7609ytwztbuf",
        "last_name": "VILLEGAS RODRIGUEZ",
        "line": "J06",
        "name": "CARLOS ABRAHAM",
        "output": "PACKING",
        "position": "ASOCIADO",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    },
    {
        "clock": "6234",
        "collectionId": "qpg7rxbw2qkd05q",
        "collectionName": "get_employess_line_record_small",
        "date": "2024-11-22",
        "employee_avatar": "",
        "employee_id": "gsjtvyiwtihf45z",
        "id": "cqe0v7cgxj3up5s",
        "last_name": "SAAVEDRA OLIVEROS",
        "line": "J08",
        "name": "JUAN LUIS",
        "output": "PACKING",
        "position": "TECNICO SMT",
        "record_position": "AU",
        "shift": "FIRST",
        "week": "47"
    }
]

wp = [
    {
        "date": "2024-11-19",
        "line": "J01",
        "planed_hours": 17,
        "target_oee": 0.75,
        "total_packing": 884,
        "total_smt_out": 894,
        "uph": 128,
        "week": 47
    },
    {
        "date": "2024-11-19",
        "line": "J02",
        "planed_hours": 17,
        "target_oee": 0.75,
        "total_packing": 1851,
        "total_smt_out": 1713,
        "uph": 260,
        "week": 47
    },
    {
        "date": "2024-11-19",
        "line": "J06",
        "planed_hours": 17,
        "target_oee": 0.78,
        "total_packing": 844,
        "total_smt_out": 816,
        "uph": 140,
        "week": 47
    },
    {
        "date": "2024-11-20",
        "line": "J01",
        "planed_hours": 23.25,
        "target_oee": 0.75,
        "total_packing": 971,
        "total_smt_out": 1034,
        "uph": 128,
        "week": 47
    },
    {
        "date": "2024-11-20",
        "line": "J02",
        "planed_hours": 13.25,
        "target_oee": 0.75,
        "total_packing": 1663,
        "total_smt_out": 1660,
        "uph": 260,
        "week": 47
    },
    {
        "date": "2024-11-20",
        "line": "J06",
        "planed_hours": 23.25,
        "target_oee": 0.78,
        "total_packing": 939,
        "total_smt_out": 1002,
        "uph": 140,
        "week": 47
    },
    {
        "date": "2024-11-20",
        "line": "J08",
        "planed_hours": 17,
        "target_oee": 0.73,
        "total_packing": 807,
        "total_smt_out": 767,
        "uph": 125,
        "week": 47
    },
    {
        "date": "2024-11-20",
        "line": "J09",
        "planed_hours": 23.25,
        "target_oee": 0.6,
        "total_packing": 646,
        "total_smt_out": 688,
        "uph": 128,
        "week": 47
    },
    {
        "date": "2024-11-21",
        "line": "J01",
        "planed_hours": 23.25,
        "target_oee": 0.75,
        "total_packing": 825,
        "total_smt_out": 884,
        "uph": 128,
        "week": 47
    },
    {
        "date": "2024-11-21",
        "line": "J02",
        "planed_hours": 23.25,
        "target_oee": 0.75,
        "total_packing": 1545,
        "total_smt_out": 1631,
        "uph": 260,
        "week": 47
    },
    {
        "date": "2024-11-21",
        "line": "J06",
        "planed_hours": 23.25,
        "target_oee": 0.78,
        "total_packing": 978,
        "total_smt_out": 948,
        "uph": 140,
        "week": 47
    },
    {
        "date": "2024-11-21",
        "line": "J08",
        "planed_hours": 23.25,
        "target_oee": 0.75,
        "total_packing": 488,
        "total_smt_out": 617,
        "uph": 140,
        "week": 47
    },
    {
        "date": "2024-11-21",
        "line": "J09",
        "planed_hours": 23.25,
        "target_oee": 0.78,
        "total_packing": 611,
        "total_smt_out": 581,
        "uph": 128,
        "week": 47
    }
]

out = []
if __name__ == "__main__":
    for _w in wp:
        print(_w)

    #find work plan
    def find_wp(line, date, output):
        for workplan in wp:

            if line in workplan["line"] and date in workplan["date"]:
                if output == "SMT_OUT":
                    return round((workplan["total_smt_out"] /((workplan['target_oee'] * workplan['uph']) * 9.25)) * 100, 2)
                else:
                    return  round((workplan["total_packing"] / ((workplan['target_oee'] * workplan['uph']) * 9.25) ) * 100,2)
        return 0


    for employee in employees:

        if len(employee["name"]) < 4:
            continue

        n_e = {
            "clock": employee["clock"],
            "name": f"{employee["name"]} {employee["last_name"]}",
            "line": employee["line"],
            "position": employee["position"],
            "shift": employee["shift"],
            "week": employee["week"],
            "date": employee["date"],
            "output": employee["output"],
            "eff":find_wp(employee["line"], employee["date"], employee["output"]),

        }


        if n_e["eff"] == 0:
            continue


        out.append(n_e)



    by_date = [] # "date": "2024-11-21"

    for e in out:
        if len(by_date) == 0:
            by_date.append({
                "date": e["date"],
                "employees": [e]
            })
        else:
            found = False
            for d in by_date:
                if d["date"] == e["date"]:
                    d["employees"].append(e)
                    found = True
                    break
            if not found:
                by_date.append({
                    "date": e["date"],
                    "employees": [e]
                })




    employee_with_data = []

    for d in by_date:
        print(d["date"])

        # group by employees_clock and add to record list
        _employee ={}
        for e in d["employees"]:
            if e["clock"] not in _employee:
                _employee[e["clock"]] = []
            _employee[e["clock"]].append(e)




        for key, records in _employee.items():

            print(key)
            _ee = {
                "clock": key,
                "name": records[0]["name"],
                "position": records[0]["position"],
                "shift": records[0]["shift"],
                "week": records[0]["week"],
                "date": records[0]["date"],
                "output": records[0]["output"],

                "eff": records[0]["eff"],
                # "eff_r": []
                #"records": records
            }

            eff_ = []

            for r in records:
                print(r)
                eff_.append(r["eff"])
                # _ee["eff_r"].append({
                #     "line": r["line"],
                #     "eff": r["eff"]
                # })

            _ee["eff"] = round(sum(eff_) / len(eff_), 2)


            employee_with_data.append(_ee)






    # employee_with_data to excel





    print(json.dumps(employee_with_data, indent=4))
